  - name: Install required packages
    yum:
      name: "{{ gitlab_dependencies }}"
      state: present
      
  - name: Enable Postfix service
    become: yes
    service:
      name: postfix 
      enabled: yes
      state: started
    notify: restart_postfix 
      
  - name: Add GitLab Repository
    shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh | sudo bash
    become: yes
    
  - set_fact: gitlab_release='gitlab-ce-{{gitlab_version}}'     
    
  - name: Install GitLab
    yum:
      name: "{{gitlab_release}}"
      state: present
   # notify:  
   #   - restart gitlab
 
#  - name: Open Firewall Ports 
#    become: yes
#    firewalld: 
#      permanent: true
#      service: "{{ item }}"
#      state: enabled
#      immediate: yes
#    with_items:
#      - http
#      - https
      
  - name: Configure GitLab URL
    lineinfile:
      path: /etc/gitlab/gitlab.rb
      line: |
        external_url "{{ gitlab_url }}"
        gitlab_rails['internal_api_url'] = '{{ gitlab_url }}'
        puma['enable'] = false
        nginx['enable'] = false
        web_server['external_users'] = ['{{ nginx_user }}']
        gitlab_rails['trusted_proxies'] = ['127.0.0.1']
        gitlab_workhorse['listen_network'] = "unix"
        gitlab_workhorse['listen_addr'] = "/var/opt/gitlab/gitlab-workhorse/sockets/socket"
        nginx['listen_port'] = 4000
        nginx['proxy_set_headers'] = {
        "X-Forwarded-Proto" => "http",
        "CUSTOM_HEADER" => "VALUE"
        }
      state: present
    notify: 
    - restart gitlab 
      
