  - name: Install nginx and certbot
    yum:
      name:
        - nginx
        - certbot
      state: present
      
  - name: Ensure nginx service is running as configured.
    service:
      name: nginx
      state: "{{ nginx_service_state }}"
      enabled: "{{ nginx_service_enabled }}"   
      
  - name: Obtain Let's Encrypt Certificate
    shell: certbot certonly --standalone -d {{ host_domain }}
    become: yes
    
  - name: Copy nginx configuration in place.
    template:
      src: "{{ nginx_conf_template }}"
      dest: "{{ nginx_conf_file_path }}"
      owner: root
      group: "{{ root_group }}"
      mode: 0644
    notify:
      - reload nginx  
 
 



