  - name: Install nginx and certbot
    yum:
      name:
        - nginx
        - certbot
      state: present  
      
  - name: Add SELinux port mapping for Grafana TCP 3000
    lineinfile:
      dest: /etc/selinux/targeted/src/policy/domains/program/tcp.te
      line: "allow http_port_t tcp_port_t:tcp_socket name_bind; # added for tcp 3000"
      insertafter: "# allow http_port_t to bind to any tcp port"
    become: yes
    
  - name: Obtain Let's Encrypt Certificate
    shell: certbot certonly --standalone -d {{ host_domain }} --email {{ letsencrypt_email }} --non-interactive --agree-tos
    become: yes
    
  - name: Copy nginx configuration in place.
    template:
      src: "{{ nginx_conf_template }}"
      dest: "{{ nginx_conf_file_path }}"
      owner: root
      group: "{{ root_group }}"
      mode: 0644
    notify:
      - Restart Nginx  
      
  - name: Insert cert-bot renew in crontab
    cron:
      name: "cert-bot renew"
      minute: 30
      hour: 1
      weekday: 1
      job: 'certbot renew --post-hook "systemctl reload nginx" >> /var/log/letsencrypt/letsencrypt-update.log 2>&1'
 
  - name: Ensure nginx service is running as configured.
    service:
      name: nginx
      state: "{{ nginx_service_state }}"
      enabled: "{{ nginx_service_enabled }}"   



