---
  - name: Install required packages
    yum:
      name:
        - wget
        - curl
        - initscripts
      state: present
      
  - name: Add Grafana Repository
    lineinfile:
      path: /etc/yum.repos.d/grafana.repo
      line: |
        [grafana]
        name=grafana
        baseurl= "{{ baseurl }}"
        repo_gpgcheck=1
        enabled=1
        gpgcheck=1
        gpgkey= "{{ gpgkey }}"
        sslverify=1
        sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        exclude=*beta*
      create: yes
      state: present

  - name: Install Grafana
    shell: yum install grafana-{{ grafana_version }}
    become: yes
    #yum:
      #name: grafana
      #state: present
      #version: "{{ grafana_version }}"

  - name: Start Grafana Service
    service:
      name: grafana-server
      state: started
      enabled: yes
