---
  - name: Install required packages
    yum:
      name: "{{ grafana_dependencies }}"
      state: present
      
  - name: Add Grafana Repository
    lineinfile:
      path: /etc/yum.repos.d/grafana.repo
      line: |
        [grafana]
        name=grafana
        baseurl= "{{ baseurl }}"
        repo_gpgcheck=1
        enabled=1
        gpgcheck=1
        gpgkey= "{{ gpgkey }}"
        sslverify=1
        sslcacert=/etc/pki/tls/certs/ca-bundle.crt
        exclude=*beta*
      create: yes
      state: present
     
  - set_fact: grafana_release='grafana-{{grafana_version}}'   

  - name: "Install Grafana {{grafana_version}}"
    yum: 
      name: "{{grafana_release}}"
      state: present
    when: grafana_version != "latest"
      
    #shell: yum install grafana-{{ grafana_version }} -y
    #become: yes   
      
  - name: Install Grafana Latest
    yum: 
      name: grafana
      state: present
    when: grafana_version == "latest"
       
  - name: Start Grafana Service
    service:
      name: grafana-server
      state: started
      enabled: yes
      
  - name: change serve_from_sub_path setting
    lineinfile:
      dest: "{{ config_dir }}/{{config_file }}"
      regexp: '^;serve_from_sub_path = false'
      line: 'serve_from_sub_path = true'
      state: present
    
  - name: change root_url setting
    lineinfile:
      dest: "{{ config_dir }}/{{config_file }}"
      regexp: '^;root_url = %(protocol)s://%(domain)s:%(http_port)s/'
      line: 'root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/'
      state: present
    notify: Restart Grafana service
