- hosts: localhost
  become: yes
  gather_facts: false
  vars:
    host_domain: quebramadeira.ddns.net
    letsencrypt_email: quebramadeira@gmail.com
  tasks:
  - name: Install community.general
    pip:
      name: community.General
      state: present
  roles:
   - nginx
   - grafana   
#   - gitlab


