- hosts: localhost
  become: yes
  gather_facts: false
  vars:
    host_domain: quebramadeira.ddns.net
    letsencrypt_email: quebramadeira@gmail.com
  roles:
   - nginx
   - grafana   
#   - gitlab


