---
- name: restart gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when | bool
  
- name: restart_postfix
  become: yes
  service:
    name: postfix
    state: restarted

- name: start_gitlab
  command: gitlab-ctl start
 
