---
root_group: root
nginx_service_state: started
nginx_service_enabled: true
nginx_conf_template: "nginx.conf.j2"
nginx_config_selinux_tcp_ports:
  - "3000"
  - "4000"

nginx_user: "nginx"
nginx_worker_processes: "auto"

nginx_pidfile: /run/nginx.pid
nginx_multi_accept: "off"

nginx_server_tokens: "off"

# events
nginx_worker_connections: "1024"

# http
nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"
nginx_types_hash_max_size: "4096"

# modular configuration files directory
nginx_conf_path: /etc/nginx/conf.d
nginx_conf_file_path: "/etc/nginx/nginx.conf"
nginx_extra_conf_options: ""

nginx_proxy_cache_path: ""
nginx_extra_http_options: ""
nginx_client_max_body_size: "64m"
nginx_server_names_hash_bucket_size: "64"

# upstreams
nginx_upstreams:
  - name: grafana
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
    servers:
      - "localhost:3000"
  - name: gitlab-workhorse
    servers:
      - "unix://var/opt/gitlab/gitlab-workhorse/sockets/socket fail_timeout=0"
